### ISSUE TITLE
M2 - Casos de prueba para eliminar producto (1 hora) [1 hora]

### ISSUE THREAD

**Issue by juanF18** [anything-devs/bike-soft-rest-api#27]

**Comment by Manuela-Rendon** [comment]
Se incluye en el [documento](https://docs.google.com/document/d/16wJGqk2l0JQ-VwMGiqBnvQZv9_QtmLV2/edit?usp=sharing&ouid=107717128985122959821&rtpof=true&sd=true) de Casos de prueba los casos de prueba diseñados.
